#pragma once

#include "esphome/core/component.h"
#include "esphome/core/gpio.h"
#include "esphome/core/preferences.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/components/text_sensor/text_sensor.h"
#include "esphome/components/binary_sensor/binary_sensor.h"
#include "../weight_sensor/weight_sensor.h"
#include "grind_config.h"
#include <driver/rmt_tx.h>
#include <driver/rmt_encoder.h>
#include <cstdint>
#include <cstring>

namespace esphome {
namespace grind_controller {

using weight_sensor::WeightSensorComponent;

// ── Grind phase state machine ─────────────────────────────────────────────────
enum class GrindPhase {
    IDLE,
    INITIALIZING,
    SETUP,
    TARING,
    TARE_CONFIRM,
    PREDICTIVE,
    PULSE_DECISION,
    PULSE_EXECUTE,
    PULSE_SETTLING,
    FINAL_SETTLING,
    TIME_GRINDING,
    TIME_ADDITIONAL_PULSE,
    COMPLETED,
    TIMEOUT,
    PRIME,
    PRIME_SETTLING,
    PURGE_CONFIRM,
};

// ── Internal pulse report ─────────────────────────────────────────────────────
struct PulseReport {
    float start_weight;
    float end_weight;
    float duration_ms;
};

// ============================================================================
// GrindController
// Single-threaded ESPHome port of GrindController + WeightGrindStrategy +
// TimeGrindStrategy.  Motor control uses IDF RMT (same as PlatformIO).
// All public API methods are callable from YAML lambdas.
// ============================================================================
class GrindController : public Component {
public:
    // ── ESPHome config setters ────────────────────────────────────────────
    void set_weight_sensor(WeightSensorComponent* ws)    { weight_sensor_ = ws; }
    void set_motor_pin(InternalGPIOPin* pin)              { motor_pin_ = pin; }
    void set_motor_settling_time_ms(uint32_t ms)          { motor_settling_time_ms_ = ms; }

    // Sub-sensor setters (generated by __init__.py)
    void set_current_weight_sensor(sensor::Sensor* s)     { s_current_weight_ = s; }
    void set_flow_rate_sensor(sensor::Sensor* s)          { s_flow_rate_ = s; }
    void set_phase_name_sensor(text_sensor::TextSensor* s){ s_phase_name_ = s; }
    void set_progress_sensor(sensor::Sensor* s)           { s_progress_ = s; }
    void set_pulse_count_sensor(sensor::Sensor* s)        { s_pulse_count_ = s; }
    void set_last_grind_error_sensor(sensor::Sensor* s)   { s_last_error_ = s; }
    void set_last_grind_duration_sensor(sensor::Sensor* s){ s_last_duration_ = s; }
    void set_last_grind_final_weight_sensor(sensor::Sensor* s) { s_last_final_ = s; }
    void set_mechanical_anomaly_sensor(sensor::Sensor* s) { s_mechanical_ = s; }
    void set_is_calibrated_sensor(binary_sensor::BinarySensor* s) { s_calibrated_ = s; }
    void set_motor_latency_sensor(sensor::Sensor* s)      { s_motor_latency_ = s; }

    // ── Component lifecycle ───────────────────────────────────────────────
    void setup() override;
    void loop() override;
    float get_setup_priority() const override { return setup_priority::DATA - 1.0f; }
    void dump_config() override;

    // ── Public grind API (YAML lambdas call these) ────────────────────────
    void start_grind_weight(float target_g, uint8_t profile_id = 0);
    void start_grind_time(float target_time_s, uint8_t profile_id = 0);
    void stop_grind();
    void continue_from_purge();
    void start_additional_pulse();
    void request_tare();
    void start_calibration(float reference_weight_g = USER_CALIBRATION_REFERENCE_WEIGHT_G);
    void start_autotune();
    void cancel_autotune();

    // ── State query (YAML lambdas) ────────────────────────────────────────
    bool is_active() const   { return phase_ != GrindPhase::IDLE; }
    bool is_grinding() const { return motor_on_; }
    GrindPhase get_phase() const { return phase_; }
    const char* get_phase_name() const { return phase_name(phase_); }
    int get_progress_percent() const;
    float get_current_weight() const;
    float get_target_weight() const { return target_weight_; }
    float get_motor_latency() const { return motor_latency_ms_; }

    // ── Configurable parameters from HA ──────────────────────────────────
    void set_target_weight(float g)        { target_weight_ = g; }
    void set_target_time_s(float s)        { target_time_ms_ = (uint32_t)(s * 1000); }
    void set_grind_mode(int m)             { mode_ = (GrindMode)m; }
    void set_chute_mode(int m)             { chute_mode_ = (GrinderPurgeMode)m; save_prefs(); }
    void set_chute_amount_g(float g)       { chute_amount_g_ = g; save_prefs(); }
    void set_freshness_hours(float h)      { freshness_hours_ = h; save_prefs(); }
    void set_motor_latency_ms(float ms)    { motor_latency_ms_ = ms; save_prefs(); }
    void set_cal_factor(float f)           { if (weight_sensor_) weight_sensor_->set_calibration_factor_runtime(f); }
    void set_swipe_enabled(bool e)         { swipe_enabled_ = e; save_prefs(); }

    // PURGE_CONFIRM state flag (read by UI YAML)
    bool is_purge_confirm() const { return phase_ == GrindPhase::PURGE_CONFIRM; }
    bool is_completed() const     { return phase_ == GrindPhase::COMPLETED; }
    bool is_timeout() const       { return phase_ == GrindPhase::TIMEOUT; }
    bool can_pulse() const {
        return mode_ == GrindMode::TIME && phase_ == GrindPhase::COMPLETED;
    }

    // ── HA event firing ───────────────────────────────────────────────────
    void fire_grind_started_event();
    void fire_grind_completed_event();

private:
    // ── Hardware references ───────────────────────────────────────────────
    WeightSensorComponent* weight_sensor_{nullptr};
    InternalGPIOPin* motor_pin_{nullptr};

    // ── ESPHome sensor outputs ────────────────────────────────────────────
    sensor::Sensor* s_current_weight_{nullptr};
    sensor::Sensor* s_flow_rate_{nullptr};
    text_sensor::TextSensor* s_phase_name_{nullptr};
    sensor::Sensor* s_progress_{nullptr};
    sensor::Sensor* s_pulse_count_{nullptr};
    sensor::Sensor* s_last_error_{nullptr};
    sensor::Sensor* s_last_duration_{nullptr};
    sensor::Sensor* s_last_final_{nullptr};
    sensor::Sensor* s_mechanical_{nullptr};
    binary_sensor::BinarySensor* s_calibrated_{nullptr};
    sensor::Sensor* s_motor_latency_{nullptr};

    // ── Grind state machine ───────────────────────────────────────────────
    GrindPhase  phase_{GrindPhase::IDLE};
    GrindMode   mode_{GrindMode::WEIGHT};
    float       target_weight_{18.0f};
    uint32_t    target_time_ms_{0};
    uint8_t     current_profile_id_{0};

    unsigned long start_time_{0};
    unsigned long phase_start_time_{0};
    unsigned long time_grind_start_ms_{0};

    // Purge / prime
    GrinderPurgeMode chute_mode_{GrinderPurgeMode::PURGE};
    float            chute_amount_g_{GRIND_PURGE_AMOUNT_DEFAULT_G};
    GrinderPurgeMode session_chute_mode_{GrinderPurgeMode::PURGE};
    float            session_chute_amount_g_{GRIND_PURGE_AMOUNT_DEFAULT_G};

    // Freshness
    float    freshness_hours_{GRIND_FRESHNESS_DEFAULT_HOURS};
    bool     purged_since_boot_{false};
    uint64_t last_grind_runtime_ms_{0};

    // Timeout
    GrindPhase    timeout_phase_{GrindPhase::IDLE};
    unsigned long timeout_pause_start_{0};
    unsigned long timeout_offset_ms_{0};

    // Predictive phase
    float   motor_stop_target_weight_{GRIND_UNDERSHOOT_TARGET_G};
    float   predictive_end_weight_{0.0f};
    float   grind_latency_ms_{0.0f};
    bool    flow_start_confirmed_{false};
    float   pulse_flow_rate_{0.0f};

    // Pulse corrections
    int   pulse_attempts_{0};
    float current_pulse_duration_ms_{0.0f};
    PulseReport pulse_history_[GRIND_MAX_PULSE_ATTEMPTS];

    // Time-mode additional pulses
    int      additional_pulse_count_{0};
    uint32_t pulse_duration_ms_{GRIND_TIME_PULSE_DURATION_MS};

    // Final weight for reporting
    float   final_weight_{0.0f};
    char    last_error_msg_[32]{};

    // Control loop paused (PURGE_CONFIRM)
    bool control_loop_paused_{false};

    // Motor state
    bool     motor_on_{false};
    unsigned long motor_start_time_{0};
    uint32_t motor_settling_time_ms_{500};

    // Mechanical instability
    int          mech_anomaly_count_{0};
    unsigned long last_mech_event_ms_{0};
    float        last_mech_weight_{0.0f};
    bool         mech_monitor_init_{false};

    // Motor latency
    float motor_latency_ms_{GRIND_MOTOR_RESPONSE_LATENCY_DEFAULT_MS};

    // Swipe gesture preference
    bool swipe_enabled_{false};

    // ── RMT motor control ─────────────────────────────────────────────────
    rmt_channel_handle_t rmt_channel_{nullptr};
    rmt_encoder_handle_t rmt_encoder_{nullptr};
    bool rmt_initialized_{false};
    bool pulse_active_{false};

    void rmt_init();
    void motor_start_continuous();
    void motor_stop();
    void motor_start_pulse(uint32_t duration_ms);
    bool motor_pulse_complete();
    bool motor_is_settled() const;

    // ── Algorithm methods ─────────────────────────────────────────────────
    void switch_phase(GrindPhase new_phase);

    // WeightGrindStrategy equivalents
    void run_predictive_phase();
    void run_pulse_decision_phase();
    void run_pulse_execute_phase();
    void run_pulse_settling_phase();
    float calculate_pulse_duration_ms(float error_g) const;
    float clamped_pulse_flow_rate() const;

    // TimeGrindStrategy equivalents
    void run_time_grinding_phase();

    // Shared helpers
    void final_measurement();
    void monitor_mechanical_instability();
    bool check_timeout() const;

    // ── Preferences persistence ───────────────────────────────────────────
    void load_prefs();
    void save_prefs();

    // ── Sensor publishing ─────────────────────────────────────────────────
    void publish_sensors();

    // ── Autotune (simplified ESPHome version) ────────────────────────────
    void autotune_update();
    bool autotune_running_{false};
    enum class AutoTuneSubPhase { IDLE, PULSE, SETTLING, DONE };
    AutoTuneSubPhase at_sub_{AutoTuneSubPhase::IDLE};
    float  at_current_ms_{0};
    float  at_step_ms_{0};
    int    at_iter_{0};
    int    at_success_{0};
    unsigned long at_phase_start_{0};

    static const char* phase_name(GrindPhase p);
};

}  // namespace grind_controller
}  // namespace esphome
